name: Pull request
on:
  pull_request:
jobs:
  check-and-test:
    name: Run code checks and tests
    runs-on: ubuntu-latest
    env:
      TURBO_REF_FILTER: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          -fetch-depth: 2

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest



      - name: Install
        run: bun install

      - name: Turbo ref filter 
        run: echo $TURBO_REF_FILTER

      - name: Show changed
        run: bun turbo run test --filter=[origin/master...HEAD] --dry-run=json

      - name: Run code cheks
        run: bun check:versions && bun check:code:root && bun check:code:packages --filter='[${{ github.event.before }}...${{ github.event.after }}]'


      - name: Run tests 
        run: bun run test --filter='[${{ github.event.before }}...${{ github.event.after }}]'


