name: Pull request
on:
  pull_request:
jobs:
  determine-affected-packages:
    name: Determine affected packages
    runs-on: ubuntu-latest
    outputs:
      affected : ${{ steps.affected-packages.outputs.var }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest


      - name: Install
        run: bun install

      - name: Determine affected packages 
        id: affected-packages
        run: echo "var=$(bun turbo run build --filter=...[origin/master] --dry-run=json | jq -r '.packages' | sed '/\/\//d' | tr -d '\n' )" >> $GITHUB_OUTPUT
  check-and-test:
    name: Run code checks and tests
    needs: determine-affected-packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: bun install

      - name: Show changed
        run: echo ${{ needs.determine-affected-packages.outputs.affected }}

