name: Pull request
on:
  pull_request:
jobs:
  check-and-test:
    name: Run code checks and tests
    runs-on: ubuntu-latest
    env:
      TURBO_RUN_FILTER: ${{ github.event_name == 'pull_request' && '...[origin/master]' || '...[HEAD^]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          -fetch-depth: 0

        with:
          bun-version: latest
      - uses: oven-sh/setup-bun@v1



      - name: Install
        run: bun install

      - name: Turbo ref filter 
        run: echo $TURBO_REF_FILTER

      - name: Show changed
        run: bun turbo run test --filter=[$TURBO_RUN_FILTER] --dry-run=json

