name: Release
run-name: chore(release) ${{github.ref_name}}
on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*@*' 
jobs:
  get-packages-to-update:
    runs-on: ubuntu-latest
    name:  Get package name, path and version
    steps:
      - name: Get the package name
        run: echo "LOCAL_PACKAGE_NAME=$( echo ${{ github.ref_name }} | cut -d "@" -f 1 )" >> $GITHUB_ENV
      - name: Print the package name 
        run: echo $LOCAL_PACKAGE_NAME
