name: Release
run-name: chore(release) ${{github.ref_name}}
on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*@*' 
jobs:
  get-packages-metadata:
    name:  Get package metadata
    runs-on: ubuntu-latest
    outputs:
      package-name : ${{ steps.get-package-name.outputs.var }}
      package-version : ${{ steps.get-package-version.outputs.var }}
      package-path : ${{ steps.get-package-path.outputs.var }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the package name
        id: get-package-name
        run: echo "var=$( echo ${{ github.ref_name }} | cut -d "@" -f 1 )" >> $GITHUB_OUTPUT

      - name: Get the package version
        id: get-packages-version
        run: echo "var=$( echo ${{ github.ref_name }} | cut -d "@" -f 2 )" >> $GITHUB_OUTPUT

      - name: Get the package path 
        id: get-package-path
        run: echo "var=$( [ -d "./apps/${LOCAL_PACKAGE_NAME}" ] && echo "apps" || echo "packages" )" >> $GITHUB_OUTPUT

  test:
    name: Check code and run tests for 
    needs: get-packages-metadata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: bun install

      - name: Run code cheks
        run: bun check:versions && bun check:code:root && bun check:code:packages --scope=${{ needs.get-packages-metadata.outputs.package-name }}

      - name: Run tests 
        run: bun run test --scope=${{ needs.get-packages-metadata.outputs.package-name }}


