name: Release
run-name: chore(release) ${{github.ref_name}}
on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*@*' 
jobs:
  get-packages-to-update:
    runs-on: ubuntu-latest
    name:  Get package name, path and version
    steps:
      - run: echo ${{ github.ref_name }}
